### ISSUE TITLE
Implementing shredding of BigData book ch 6.4 pail ok pailtap failing in jcascalog in hadoop under EMR

### ISSUE THREAD

**Issue by ljackson** [nathanmarz/dfs-datastores#19]
after my snapshot code the jcascalog I am trying to run the shredding code from the BigData book ch 6.4 new data ingesting and getting exception 

13/03/05 04:29:30 INFO property.AppProps: using app.id: 08B3BC844098F47C728E28BB3D46FF5A
Exception in thread "main" cascading.flow.planner.PlannerException: could not build flow from assembly: [java.io.NotSerializableException: com.google.protobuf.ExtensionRegistry]
        at cascading.flow.planner.FlowPlanner.handleExceptionDuringPlanning(FlowPlanner.java:515)
        at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:230)
        at cascading.flow.FlowConnector.connect(FlowConnector.java:454)
        at cascalog.api$compile_flow.doInvoke(api.clj:190)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:601)
        at cascalog.api$_QMARK__.doInvoke(api.clj:204)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:419)
        at clojure.lang.AFn.applyToHelper(AFn.java:163)
        at clojure.lang.Var.applyTo(Var.java:532)
        at jcascalog.Api.execute(Unknown Source)
        at jcascalog.Api.execute(Unknown Source)
        at jcascalog.Api.execute(Unknown Source)
        at NewPailToMasterPail$.appendNewDataToMasterDataPail(NewPailToMasterPail.scala:42)
        at NewPailToMasterPail$delayedInit$body.apply(NewPailToMasterPail.scala:30)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:60)
        at scala.App$$anonfun$main$1.apply(App.scala:60)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
        at scala.collection.immutable.List.foreach(List.scala:76)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:30)
        at scala.App$class.main(App.scala:60)
        at NewPailToMasterPail$.main(NewPailToMasterPail.scala:20)
        at NewPailToMasterPail.main(NewPailToMasterPail.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:187)
Caused by: java.lang.RuntimeException: java.io.NotSerializableException: com.google.protobuf.ExtensionRegistry
        at com.backtype.support.Utils.serialize(Utils.java:92)
        at com.backtype.support.Utils.setObject(Utils.java:74)
        at com.backtype.cascading.tap.PailTap$PailScheme.sinkConfInit(PailTap.java:131)
        at com.backtype.cascading.tap.PailTap$PailScheme.sinkConfInit(PailTap.java:68)
        at cascading.tap.Tap.sinkConfInit(Tap.java:198)
        at cascading.tap.hadoop.Hfs.sinkConfInit(Hfs.java:380)
        at com.backtype.cascading.tap.PailTap.sinkConfInit(PailTap.java:261)
        at com.backtype.cascading.tap.PailTap.sinkConfInit(PailTap.java:41)
        at cascading.flow.hadoop.HadoopFlowStep.initFromSink(HadoopFlowStep.java:423)
        at cascading.flow.hadoop.HadoopFlowStep.getInitializedConfig(HadoopFlowStep.java:101)
        at cascading.flow.hadoop.HadoopFlowStep.createFlowStepJob(HadoopFlowStep.java:201)
        at cascading.flow.hadoop.HadoopFlowStep.createFlowStepJob(HadoopFlowStep.java:69)
        at cascading.flow.planner.BaseFlowStep.getFlowStepJob(BaseFlowStep.java:605)
        at cascading.flow.BaseFlow.initializeNewJobsMap(BaseFlow.java:1172)
        at cascading.flow.BaseFlow.initialize(BaseFlow.java:184)
        at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:224)
        ... 29 more
Caused by: java.io.NotSerializableException: com.google.protobuf.ExtensionRegistry
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1164)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1518)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1483)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1400)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1158)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1518)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1483)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1400)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1158)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:330)
        at com.backtype.support.Utils.serialize(Utils.java:88)
        ... 44 more

as my DataPail has a protobuf message extension vs just a single message type as in the example at least this is my theory. My storage system works fine creating the pails and pushing them out... as well as the Map creating the snapshot rips thru the new pail without issues

1.3.0 of dfs-datastore / dfs-datastore-cascading and 2.0.7 of cascading

Relevant code from scala wrapper I am using:

  def openPlatformEventPailTap(path: String):PailTap = {
    val opts = new PailTapOptions()
    opts.spec = new PailSpec(new PlatformEventPailStructure)
    return new PailTap(path, opts)
  }

object NewPailToMasterPail extends App with Logging {
  val pailStructure = new PlatformEventPailStructure
  val pailNewData = openS3PailHelper(pailStructure, "/pail/new")
  val pailMasterData = openS3PailHelper(pailStructure, "/pail/master")

  //This will be in HDFS from EMR
  val snapshotPath = "/pail/snapshot"
  val shreddedPath = "/pail/shredded"
  val snapshotPail = pailNewData.snapshot(snapshotPath)

  appendNewDataToMasterDataPail(pailMasterData)
  pailNewData.deleteSnapshot(snapshotPail)

  def appendNewDataToMasterDataPail(masterPail: Pail[PlatformEvents.PlatformBaseEvent]): Unit = {
    //Shred step -- Reorganizing a Pail to have a new structure is called "shredding".
    val source = openPlatformEventPailTap(snapshotPath)
    val sink = openPlatformEventPailTap(shreddedPath)
    val reduced = new Subquery("?rand", "?data")
      .predicate(source, "_", "?data-in")
      .predicate(new RandLong(), "?rand")
      .predicate(new IdentityBuffer(), "?data-in").out("?data");
    Api.execute(
      sink,
      new Subquery("?data")
        .predicate(reduced, "_", "?data"));

```
//Reduce the new pail files step two
val shreddedPail = new Pail(shreddedPath)
shreddedPail.consolidate()

//Append to the master dataset step three
masterPail.absorb(shreddedPail)
```

  }
}

protobuf definitions are something like....

http://blog.wolfman.com/articles/2011/11/23/how-to-implement-polymorphic-protocol-buffers-in-java

**Comment by ljackson** [comment]
I think I have found the issue. will close or update once I verify.

**Comment by ljackson** [comment]
yep had a non-serializable member object in my PailStructure implementation. Sorry to bother you.

**Comment by sritchie** [comment]
What was the issue?

**Comment by ljackson** [comment]
So for some reason when working with normal Pail's all is fine however in cascading.flow.planner.FlowPlanner or jcascalog in the code above try's to serialize the PailStructure and I had a non serializable member variable in there, it only happens with the jscascalog query and the PailTap using my PailStructure. As seen by the exception it was telling me the google protobuf ExtentsionRegistry I had in my pail structure is not serializable but what I didn't expect is that class implementing the PailStructure to be serialized. Something about the flow and the M/R job created by Jcascalog must require it is the only thing I can come up with.
